### ISSUE TITLE
Fix mobx-binder es6 issues with jest

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/create-react-cy-app#17]
When running `yarn test` while including mobx-binder it fails as there are es6 errors, `import` is nog recognized.
We already fixed this with a react-native app, but this setup is so complicated that I have no idea where to start

**Comment by SpaceK33z** [comment]
Yeah we fixed this with a hack in a react-native app. I've fixed it properly now in mobx-spine (see https://github.com/CodeYellowBV/mobx-spine/commit/513ff8b0e87b8b0611e81cfb8fdafa4794457e03).

Upgrade to `mobx-spine@0.2.1` to get the fix.
