### ISSUE TITLE
Debugger is off by 6 lines

### ISSUE THREAD

**Issue by stam** [CodeYellowBV/create-react-cy-app#18]
When placing a debugger, in the chrome devtools, the line 6 lines below the debugger is highlighted.

<img width="367" alt="screen shot 2017-03-08 at 13 04 58" src="https://cloud.githubusercontent.com/assets/12035356/23703368/dce9bdd0-03ff-11e7-96e6-76e1ca1743f3.png">

**Comment by SpaceK33z** [comment]
There are several known issues with source maps and webpack at the moment. So we'll need to wait on that.

**Comment by SpaceK33z** [comment]
Related bug in create-react-app: https://github.com/facebookincubator/create-react-app/issues/1638#issuecomment-283251622
