### ISSUE TITLE
Not supporting old browsers

### ISSUE THREAD

**Issue by Taym95** [CodeYellowBV/create-react-cy-app#27]
Hey @SpaceK33z, this repository is not supporting old chrome versions, I tried to play a little bit with babel but still have the same issue any idea?

**Comment by SpaceK33z** [comment]
If you add the environment variable `LEGACY_BROWSERS=true` to your build script it should work.

**Comment by Taym95** [comment]
Thank you for responding, I added `LEGACY_BROWSERS=true` but I still can't run the app on chrome
v < 50, I tried to create a simple create-react-app app and it works.
